apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migration
  namespace: cluster-manager
spec:
  backoffLimit: 5
  template:
    metadata:
      labels:
        app: backend-migration
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migration
          image: ghcr.io/yasaman-saffar/cluster-manager-backend:main
          imagePullPolicy: Always
          command: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"