# Generated by Django 6.0.8 on 2026-09-05 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_rename_cron_periodicbackup_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='container_port',
        ),
    ]
